# Generated by Django 4.2.4 on 2023-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='author',
            name='info',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
